version: "3.9"

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/acme.json:/acme.json
      - ./traefik/dynamic_redirects.yml:/traefik/dynamic_redirects.yml:ro
    networks:
      - app_network
    labels:
      - "traefik.enable=true"

  nextjs:
    image: nextjs:latest
    container_name: nextjs
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`lundbeck.vs113.ru`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    networks:
      - app_network
    expose:
      - "3000"

networks:
  app_network:
    driver: bridge