entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: tech@frizar.ru
      storage: acme.json
      httpChallenge:
        entryPoint: web